version: '3.1'
services:
  mongo:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cualquiera
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: cualquiera

    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
volumes:
    data: